/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
}

repositories {
    maven {
        url = uri("https://plugins.gradle.org/m2/")
    }
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    implementation("com.google.code.gson:gson:2.7")

    implementation("org.xerial:sqlite-jdbc:3.47.0.0")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sourceCompatibility = 21

targetCompatibility = 21

application {
    // Define the main class for the application.
    mainClass = "org.superstudy.backend.v1.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
